\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{}
    \pretitle{\vspace{\droptitle}}
  \posttitle{}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  

\begin{document}

\hypertarget{the-wine-geek-analysis}{%
\section{The Wine Geek Analysis}\label{the-wine-geek-analysis}}

\hypertarget{by-jean-phelippe-ramos-de-oliveira-jean.phelippe92gmail.com}{%
\subparagraph{\texorpdfstring{by Jean Phelippe Ramos de Oliveira
(\href{mailto:jean.phelippe92@gmail.com}{\nolinkurl{jean.phelippe92@gmail.com}})}{by Jean Phelippe Ramos de Oliveira (jean.phelippe92@gmail.com)}}\label{by-jean-phelippe-ramos-de-oliveira-jean.phelippe92gmail.com}}

\hypertarget{abstract}{%
\section{Abstract}\label{abstract}}

\begin{quote}
We know that taste is very difficult to map and understand as different
people have different preferences. However, at the same time, it's well
known that wines can have different levels of quality that yield a whole
span of different prices. The goal of this document is to present a
technical analysis over physical and chemical variables from Portuguese
wines and try to shed some light on the relationships between
physicochemical properties of wine and the rates given to the wines by
wine experts.
\end{quote}

\emph{We have deleted the variable listing the IDs.}

\hypertarget{univariate-plots-section}{%
\section{Univariate Plots Section}\label{univariate-plots-section}}

Below we can find a summary statistics of all variables:

\begin{verbatim}
##  fixed.acidity   volatile.acidity  citric.acid    residual.sugar  
##  Min.   : 4.60   Min.   :0.1200   Min.   :0.000   Min.   : 0.900  
##  1st Qu.: 7.10   1st Qu.:0.3900   1st Qu.:0.090   1st Qu.: 1.900  
##  Median : 7.90   Median :0.5200   Median :0.260   Median : 2.200  
##  Mean   : 8.32   Mean   :0.5278   Mean   :0.271   Mean   : 2.539  
##  3rd Qu.: 9.20   3rd Qu.:0.6400   3rd Qu.:0.420   3rd Qu.: 2.600  
##  Max.   :15.90   Max.   :1.5800   Max.   :1.000   Max.   :15.500  
##    chlorides       free.sulfur.dioxide total.sulfur.dioxide
##  Min.   :0.01200   Min.   : 1.00       Min.   :  6.00      
##  1st Qu.:0.07000   1st Qu.: 7.00       1st Qu.: 22.00      
##  Median :0.07900   Median :14.00       Median : 38.00      
##  Mean   :0.08747   Mean   :15.87       Mean   : 46.47      
##  3rd Qu.:0.09000   3rd Qu.:21.00       3rd Qu.: 62.00      
##  Max.   :0.61100   Max.   :72.00       Max.   :289.00      
##     density             pH          sulphates         alcohol     
##  Min.   :0.9901   Min.   :2.740   Min.   :0.3300   Min.   : 8.40  
##  1st Qu.:0.9956   1st Qu.:3.210   1st Qu.:0.5500   1st Qu.: 9.50  
##  Median :0.9968   Median :3.310   Median :0.6200   Median :10.20  
##  Mean   :0.9967   Mean   :3.311   Mean   :0.6581   Mean   :10.42  
##  3rd Qu.:0.9978   3rd Qu.:3.400   3rd Qu.:0.7300   3rd Qu.:11.10  
##  Max.   :1.0037   Max.   :4.010   Max.   :2.0000   Max.   :14.90  
##     quality     
##  Min.   :3.000  
##  1st Qu.:5.000  
##  Median :6.000  
##  Mean   :5.636  
##  3rd Qu.:6.000  
##  Max.   :8.000
\end{verbatim}

In our case, there is only one categorical variable which is quality
(integers between 0 and 10).

\includegraphics{project_final_jean_files/figure-latex/unnamed-chunk-3-1.pdf}

Let's start by analyzing the quality:

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   3.000   5.000   6.000   5.636   6.000   8.000
\end{verbatim}

As we can see, the median is around the rating 6.0 with the best wine
rated at 8.0. Which means that's very difficult to find good wines
(\textgreater{}7) in this dataset as per statistical analysis. The plot
shows that majority of wines are rates between 5 or 6. This also means
that our analysis may be biased towards lower quality wines.

\includegraphics{project_final_jean_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    8.40    9.50   10.20   10.42   11.10   14.90
\end{verbatim}

The minimum alcohol percentage by volume is 8.4 and it ranges up to
14.90. The dataset is skewed towards the range of 10\%, which is
reasonable for most wines I know. I wonder if alcohol levels are
actually relevant for a good rating as stronger wines may be more
difficult to appreciate. Also it is a substance that evaporates easily
and can affect smell.

\includegraphics{project_final_jean_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1.00    7.00   14.00   15.87   21.00   72.00
\end{verbatim}

Free SO2 is also spread across a wide range. The minimum is 1 and
maxiumum goes to 72 mg/dm\^{}3. There is a higher concentration in the
range of 7-20 mg/dm\^{}3. This substance is related to oxidation of the
wine and it's well known that the oxidation affects the wine taste.

\includegraphics{project_final_jean_files/figure-latex/unnamed-chunk-8-1.pdf}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    6.00   22.00   38.00   46.47   62.00  289.00
\end{verbatim}

Total SO2 has a wide range of values with the Maximum at 289mg/dm³.
Minimum at 6mg/dm³ and mean around 46mg/dm³ (highr than free SO2 as
expected once free SO2 should be a part of the total)

\includegraphics{project_final_jean_files/figure-latex/unnamed-chunk-10-1.pdf}

After applying a log10 transformation to the plot we can now reduce the
effect of the long tail and clearly see a more normal distribution
around the value of 30g/dm³

\includegraphics{project_final_jean_files/figure-latex/unnamed-chunk-11-1.pdf}

\includegraphics{project_final_jean_files/figure-latex/unnamed-chunk-12-1.pdf}

\includegraphics{project_final_jean_files/figure-latex/unnamed-chunk-13-1.pdf}

Fixed and Volatile acidity show up with two peaks around 7-8g/dm³ for
fixed and 0.4-0.6g/dm³. Fixed acidity ranges from 4.6 up to almost
16g/dm³ but the mean is around 8g/dm³. The Volatile acidity ranges from
0.12-1.58g/dm³ with Mean around 0.52g/dm³. Higher levels of volatile
acidity (usually linked with acetic acid) can yield a bad taste
(vinegar-like taste). The amount of non-volatile acid is way higher,
because they compose the bulk of acidity on a wine.

Citric acid levels can be found at higher range than acetic acid, but
they are still small compared to non-volatile. It ranges from 0-1g/dm³.

\includegraphics{project_final_jean_files/figure-latex/unnamed-chunk-14-1.pdf}

pH levels range from 2.74 to 4.01 which are within the acid range
exactly as we expect from wines.

\includegraphics{project_final_jean_files/figure-latex/unnamed-chunk-15-1.pdf}

Chlorides usually are liked to the salty taste and should be found on
small quantities. They range from 0.012 up to 0.611 with median around
0.08g/dm³. It can vary up to 50 time from the minimum up to maximum
values on this dataset.

\includegraphics{project_final_jean_files/figure-latex/unnamed-chunk-16-1.pdf}

Higher quality wines seem to have a more concentrated range of chlorides
\textless{}0.1 but we still need to dive deeper into the data to check
if there's any relationship between variables.

\hypertarget{univariate-analysis}{%
\section{Univariate Analysis}\label{univariate-analysis}}

\hypertarget{what-is-the-structure-of-your-dataset}{%
\subsubsection{What is the structure of your
dataset?}\label{what-is-the-structure-of-your-dataset}}

\begin{verbatim}
##  [1] "fixed.acidity"        "volatile.acidity"     "citric.acid"         
##  [4] "residual.sugar"       "chlorides"            "free.sulfur.dioxide" 
##  [7] "total.sulfur.dioxide" "density"              "pH"                  
## [10] "sulphates"            "alcohol"              "quality"
\end{verbatim}

\textbf{Variables}:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  fixed acidity (tartaric acid - g / dm\^{}3)
\item
  volatile acidity (acetic acid - g / dm\^{}3)
\item
  citric acid (g / dm\^{}3)
\item
  residual sugar (g / dm\^{}3)
\item
  chlorides (sodium chloride - g / dm\^{}3
\item
  free sulfur dioxide (mg / dm\^{}3)
\item
  total sulfur dioxide (mg / dm\^{}3)
\item
  density (g / cm\^{}3)
\item
  pH
\item
  sulphates (potassium sulphate - g / dm3)
\item
  alcohol (\% by volume)
\item
  quality (score between 0 and 10)
\end{enumerate}

According to the list above, we have 12 variables in which the first 11
are physicochemical properties that were measured and a final variable
called quality that was a rate from 0 (very bad) to 10 (excellent) given
by at least 3 wine experts. There are 1599 observations in this dataset.
Most of the wines are in average quality (5-6 quality rates).

\hypertarget{what-isare-the-main-features-of-interest-in-your-dataset}{%
\subsubsection{What is/are the main feature(s) of interest in your
dataset?}\label{what-isare-the-main-features-of-interest-in-your-dataset}}

The main feature that is common to our knowldege and of many people that
appreciate drinks is the \texttt{alcohol\ level}. We'd like to evaluate
the correlation between alcohol levels and quality and use other
variable to understand the dynamic of the quality as we believe that
there's a limit in which the alcohol level can affect taste positively.

\hypertarget{what-other-features-in-the-dataset-do-you-think-will-help-support-your}{%
\subsubsection{\texorpdfstring{What other features in the dataset do you
think will help support your\\
}{What other features in the dataset do you think will help support your }}\label{what-other-features-in-the-dataset-do-you-think-will-help-support-your}}

investigation into your feature(s) of interest?

It's a geeky analysis as there can be way more other variables that can
affect the tast of wine such as temperature and how long the wine was in
contact with oxygen. However, for this analysis we really want to focus
on physicochecmical properties. We think that looking at common
properties that we analyze in a wine such as alcohol percentage, acidity
levels (including pH), total sulfur dioxide (related to oxidation) and
residual sugar (related to sweetness) may be the most impactful ones.

\hypertarget{did-you-create-any-new-variables-from-existing-variables-in-the-dataset}{%
\subsubsection{Did you create any new variables from existing variables
in the
dataset?}\label{did-you-create-any-new-variables-from-existing-variables-in-the-dataset}}

Based on the description of the dataset, turns out that wines with
levels of free SO2 higher than 50ppm (or mg/dm³) may have their taste
affected. The SO2 mainly helps prevent oxidation, but can affect the
taste if in high contration. Thus, we've created a categorical variable
called \texttt{level.free.sulfur.dioxide} that splits the dataset into
High(\textgreater{}50ppm) and Low (\textless{}=50ppm) levels of free
SO2.

\hypertarget{of-the-features-you-investigated-were-there-any-unusual-distributions}{%
\subsubsection{\texorpdfstring{Of the features you investigated, were
there any unusual distributions?\\
}{Of the features you investigated, were there any unusual distributions? }}\label{of-the-features-you-investigated-were-there-any-unusual-distributions}}

Did you perform any operations on the data to tidy, adjust, or change
the form\\
of the data? If so, why did you do this?

Fixed and volatile acidity have shown 2 peaks each. Whereas Total SO2
has shown a long tail shape. We applied the log10 transform to total SO2
in order to reduce the skewness from the long tail and try to visualize
it a more normal shape.

\hypertarget{bivariate-plots-section}{%
\section{Bivariate Plots Section}\label{bivariate-plots-section}}

\begin{quote}
\textbf{Tip}: Based on what you saw in the univariate plots, what
relationships between variables might be interesting to look at in this
section? Don't limit yourself to relationships between a main output
feature and one of the supporting variables. Try to look at
relationships between supporting variables as well.
\end{quote}

We can plot a few of the variables above in order to look for outliers.
Variables such as \texttt{total.sulfur.dioxide} and
\texttt{residual.sugar} presents a Maximum value that is way higher than
their 3rd Quartile, which suggests some outliers.

\hypertarget{bivariate-analysis}{%
\section{Bivariate Analysis}\label{bivariate-analysis}}

\begin{quote}
\textbf{Tip}: As before, summarize what you found in your bivariate
explorations here. Use the questions below to guide your discussion.
\end{quote}

\hypertarget{talk-about-some-of-the-relationships-you-observed-in-this-part-of-the}{%
\subsubsection{\texorpdfstring{Talk about some of the relationships you
observed in this part of the\\
}{Talk about some of the relationships you observed in this part of the }}\label{talk-about-some-of-the-relationships-you-observed-in-this-part-of-the}}

investigation. How did the feature(s) of interest vary with other
features in\\
the dataset?

\hypertarget{did-you-observe-any-interesting-relationships-between-the-other-features}{%
\subsubsection{\texorpdfstring{Did you observe any interesting
relationships between the other features\\
}{Did you observe any interesting relationships between the other features }}\label{did-you-observe-any-interesting-relationships-between-the-other-features}}

(not the main feature(s) of interest)?

\hypertarget{what-was-the-strongest-relationship-you-found}{%
\subsubsection{What was the strongest relationship you
found?}\label{what-was-the-strongest-relationship-you-found}}

\hypertarget{multivariate-plots-section}{%
\section{Multivariate Plots Section}\label{multivariate-plots-section}}

\begin{quote}
\textbf{Tip}: Now it's time to put everything together. Based on what
you found in the bivariate plots section, create a few multivariate
plots to investigate more complex interactions between variables. Make
sure that the plots that you create here are justified by the plots you
explored in the previous section. If you plan on creating any
mathematical models, this is the section where you will do that.
\end{quote}

\hypertarget{multivariate-analysis}{%
\section{Multivariate Analysis}\label{multivariate-analysis}}

\hypertarget{talk-about-some-of-the-relationships-you-observed-in-this-part-of-the-1}{%
\subsubsection{\texorpdfstring{Talk about some of the relationships you
observed in this part of the\\
}{Talk about some of the relationships you observed in this part of the }}\label{talk-about-some-of-the-relationships-you-observed-in-this-part-of-the-1}}

investigation. Were there features that strengthened each other in terms
of\\
looking at your feature(s) of interest?

\hypertarget{were-there-any-interesting-or-surprising-interactions-between-features}{%
\subsubsection{Were there any interesting or surprising interactions
between
features?}\label{were-there-any-interesting-or-surprising-interactions-between-features}}

\hypertarget{optional-did-you-create-any-models-with-your-dataset-discuss-the}{%
\subsubsection{\texorpdfstring{OPTIONAL: Did you create any models with
your dataset? Discuss the\\
}{OPTIONAL: Did you create any models with your dataset? Discuss the }}\label{optional-did-you-create-any-models-with-your-dataset-discuss-the}}

strengths and limitations of your model.

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{final-plots-and-summary}{%
\section{Final Plots and Summary}\label{final-plots-and-summary}}

\begin{quote}
\textbf{Tip}: You've done a lot of exploration and have built up an
understanding of the structure of and relationships between the
variables in your dataset. Here, you will select three plots from all of
your previous exploration to present here as a summary of some of your
most interesting findings. Make sure that you have refined your selected
plots for good titling, axis labels (with units), and good aesthetic
choices (e.g.~color, transparency). After each plot, make sure you
justify why you chose each plot by describing what it shows.
\end{quote}

\hypertarget{plot-one}{%
\subsubsection{Plot One}\label{plot-one}}

\hypertarget{description-one}{%
\subsubsection{Description One}\label{description-one}}

\hypertarget{plot-two}{%
\subsubsection{Plot Two}\label{plot-two}}

\hypertarget{description-two}{%
\subsubsection{Description Two}\label{description-two}}

\hypertarget{plot-three}{%
\subsubsection{Plot Three}\label{plot-three}}

\hypertarget{description-three}{%
\subsubsection{Description Three}\label{description-three}}

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{reflection}{%
\section{Reflection}\label{reflection}}

\begin{quote}
\textbf{Tip}: Here's the final step! Reflect on the exploration you
performed and the insights you found. What were some of the struggles
that you went through? What went well? What was surprising? Make sure
you include an insight into future work that could be done with the
dataset.
\end{quote}

\begin{quote}
Citation: P. Cortez, A. Cerdeira, F. Almeida, T. Matos and J. Reis.
Modeling wine preferences by data mining from physicochemical
properties. In Decision Support Systems, Elsevier, 47(4):547-553. ISSN:
0167-9236.
\end{quote}


\end{document}
